general_configuration:
  sbml_model_name: "TEST_1_1_antiporter_cycle1"
  sbml_model_file: "/Users/georgeau/Desktop/GitHub/Bayesian_Transporter/new/antiporter_1_1_12D_cycle1/antiporter_1_1_12D_cycle1_sbml.xml"
  observed_data_file: "/Users/georgeau/Desktop/GitHub/Bayesian_Transporter/new/antiporter_1_1_12D_cycle1/experiment1/antiporter_1_1_12D_cycle1_experiment1_data.csv"
  random_seed: 42

experiment_simulation_configuration:
  experiment_name: "experiment1and2"
  buffer_species_names: ["conc_H_out", "conc_S_out"]
  buffer_concentration_sequence: [[1.e-7,1.e-3],[5.e-7,1.e-3],[1.e-7,1.e-3],[5.e-7,0.500e-3],[1.e-7,1.e-3]]
  buffer_concentration_scale: [1,1]
  time_per_stage: 1
  n_points_per_stage: 200
  remove_first_n: 1
  remove_after_n: 100
  sbml_model_parameter_names: ["k1_f_0", "k1_r_0", "k2_f_0", "k2_r_0", "k3_f_0", "k3_r_0", "k4_f_0", "k4_r_0", "k5_f_0", "k5_r_0", "k6_f_0"]
  species_labels: ["conc_OF", "conc_OF_Hb", "conc_IF_Hb", "conc_IF_Hb_Sb", "conc_IF_Sb", "conc_OF_Sb", "conc_H_in", "conc_S_in"]
  species_initial_concentrations: [ 0.0004369941792375325, 0, 0, 0, 0, 0, 1.e-7, 1.e-3]
  species_initial_concentrations_scale: [1, 1, 1, 1, 1, 1, 1, 1]
  solver_absolute_tolerance: 1.e-15
  solver_relative_tolerance: 1.e-12
  roadrunner_solver_output_selections: ["time","net_ion_influx"]

optimization_and_inference:
  optimization_and_inference_name: "optimization_survey_extended"
  use_extended: True
  use_optimization: True
  use_mcmc: False

  optimization_arguments:
    objective_function_module: "transporter_functions"
    objective_function_name: "calc_neg_log_posterior_wrapper"
    method: 
    - "Nelder-Mead"
    - "L-BFGS-B"
    - "TNC"
    - "SLSQP"
    - "Powell"
    - "trust-constr"
    - "differential_evolution"
    - "basinhopping"
    - "dual_annealing"
    - "direct"
    n_replicas: 10

  mcmc_arguments: 
    method: "pocomc"
    n_walkers: 1000
    thin: 10
    burn_in: 1
    ess: 0.95
    gamma: 0.75
    additional_samples: 10000
    n_max: 1000
    n_replicas: 1

  parameters:
    - name: "log10_k1_f"
      bounds: [6,12]
      nominal: 10
    - name: "log10_k1_r"
      bounds: [-1, 5]
      nominal: 3
    - name: "log10_k2_f"
      bounds: [-2, 4]
      nominal: 2
    - name: "log10_k2_r"
      bounds: [-2, 4]
      nominal: 2
    - name: "log10_k3_f"
      bounds: [3,9]
      nominal: 7
    - name: "log10_k3_r"
      bounds: [-1, 5]
      nominal: 3
    - name: "log10_k4_f"
      bounds: [-1, 5]
      nominal: 3
    - name: "log10_k4_r"
      bounds: [6,12]
      nominal: 10
    - name: "log10_k5_f"
      bounds: [-2,4]
      nominal: 2
    - name: "log10_k5_r"
      bounds: [-2,4]
      nominal: 2
    - name: "log10_k6_f"
      bounds: [-1,5]
      nominal: 3
    - name: "H_out_scale"
      bounds: [0.8,1.2]
      nominal: 1
    - name: "S_out_scale"
      bounds: [0.8,1.2]
      nominal: 1
    - name: "protein_conc_scale"
      bounds: [0.8,1.2]
      nominal: 1
    - name: "bias_scale"
      bounds: [0.8,1.2]
      nominal: 1
    - name: "log10_sigma"
      bounds: [-8.3, -6.3]
      nominal: -7.3





        
        
       
        
       
        
       
